HOST = "127.0.0.1"  # Standard loopback interface address (localhost)
PORT = 65431 # Port to listen on (non-privileged ports are > 1023)
IMG_WIDTH = 28
IMG_HEIGHT = 28
IMG_SZ = IMG_HEIGHT * IMG_WIDTH
LAYER_1 = 300
# OUTPUT_LAYER = 1
LABEL_CNT = 10
ENCRYPTION = False